"""empty message

Revision ID: a3d644eef903
Revises: 27eb30245c40
Create Date: 2025-06-16 20:40:58.618739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3d644eef903'
down_revision = '27eb30245c40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('preview', sa.String(length=5), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_id'), ['id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=256), nullable=False))
        batch_op.create_index('ix_user_email', ['email'], unique=1)

    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_id'))

    op.drop_table('email')
    # ### end Alembic commands ###
